/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [{type: 'autogenerated', dirName: '.'}],

  // defaultSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: '物理引擎学习',
  //     items: [{ type: 'autogenerated', dirName: 'physical-engine-study' }],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Tutorial Basics',
  //     items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Tutorial Extras',
  //     items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
  //   },
  // ],
};

module.exports = sidebars;
